FROM php:8-apache

WORKDIR /var/www

RUN apt-get update \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysqli \
    && docker-php-ext-enable mysqli

EXPOSE 80

RUN a2enmod rewrite
