version: '3'

services:
  mysql:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql:Z
    environment:
       - MYSQL_ROOT_PASSWORD=passw
       - MYSQL_DATABASE=banco

