/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package teste_unitario;

public class App {
    public static void main(String[] args) {
        Calculadora calculadora = new Calculadora();

        Double soma = calculadora.soma(10D, 10D);
        boolean resultado = soma == 20D;

        System.out.println(resultado);
    }
}
