/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package daorepository;

import java.sql.Connection;

import daorepository.model.ContatoVO;
import daorepository.model.dao.ConexaoFactory;
import daorepository.model.dao.ContatoDAO;
import daorepository.repositories.ContatoRepositoryMemoria;
import daorepository.repositories.ContatoRepositoryMySQL;
import daorepository.repositories.interfaces.IContatoRepository;
import daorepository.services.ContatoService;

public class App {
    public static void main(String[] args) throws Exception {
        Connection connection = ConexaoFactory.getConexao();

        ContatoDAO contatoDAO = new ContatoDAO(connection);
        contatoDAO.migrate();

        IContatoRepository contatoRepositoryMySQL = new ContatoRepositoryMySQL(contatoDAO);
        ContatoService contatoService = new ContatoService(contatoRepositoryMySQL);

        contatoService.salvar(new ContatoVO(null, "Teste", "Teste@teste.com", "99999999"));
        contatoService.atualizar(new ContatoVO(1, "Teste 2", "Teste@teste.com", "98989898"));
        System.out.println(contatoService.buscarTodos());
        System.out.println(contatoService.buscarPorEmail("Teste@teste.com"));

        IContatoRepository contatoRepositoryMemoria = new ContatoRepositoryMemoria();
        ContatoService contatoService2 = new ContatoService(contatoRepositoryMemoria);

        contatoService2.salvar(new ContatoVO(null, "Teste", "Teste@teste.com", "99999999"));
        contatoService2.salvar(new ContatoVO(null, "Teste 3", "Teste3@teste.com", "99999999"));
        contatoService2.salvar(new ContatoVO(null, "Teste 4", "Teste4@teste.com", "99999999"));
        contatoService2.atualizar(new ContatoVO(1, "Teste 2", "Teste@teste.com", "98989898"));
        System.out.println(contatoService2.buscarTodos());
        System.out.println(contatoService2.buscarPorEmail("Teste@teste.com"));
    }
}
