version: '3.1'

services:
  fatec_cpp:
    image: gcc:11.1-bullseye
    volumes:
      - ./Algoritimos e Lógica de Programação/C++/:/scripts/cpp/algoritimos/:Z
      - ./Estruturas de dados/:/scripts/cpp/estruturas_de_dados/:Z
    working_dir: /scripts/cpp
    tty: true

  fatec_mariadb:
    image: mariadb:10.8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./database/:/var/lib/mysql/:Z
      - ./Bancos de dados relacionais/:/scripts/mysql/bancos_relacionais/:Z
      - ./Modelagem de Bancos de Dados/SQL/:/scripts/mysql/modelagem_de_bancos/:Z
    working_dir: /scripts/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  fatec_java:
    image: openjdk:11
    volumes:
      - ./Técnicas de programação 1/:/scripts/java/tecnicas_1/:Z
      - ./Técnicas de programação 2/:/scripts/java/tecnicas_2/:Z
    working_dir: /scripts/java
    tty: true

  fatec_php:
    build:
      context: .
      dockerfile: Dockerfile_php_apache
    ports:
      - 80:80
    volumes:
      - ./Desenvolvimento web 2/:/var/www/:Z
      - ./Desenvolvimento web 2/:/var/www/html/:Z
    tty:
      true

  fatec_python:
    image: python:3.10-alpine
    tty: true
    working_dir: /scripts/python/dev_3/
    volumes:
      - ./Desenvolvimento web 3/:/scripts/python/dev_3/:Z
    ports:
      - 8000:8000
