NUM_NODE = 1
IMAGE_BOX = "ubuntu/bionic64"
NODE_NAME = "svr"
NODE_MEM = 1024
NODE_CPU = 1

IP_NW = "192.168.56."
NODE_IP_START = 10

Vagrant.configure("2") do |config|
  config.vm.box = "#{IMAGE_BOX}"
  config.vm.box_check_update = false

  (1..NUM_NODE).each do |i|
    config.vm.define "#{NODE_NAME}0#{i}" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "#{NODE_NAME}#{i}"
            vb.memory = "#{NODE_MEM}"
            vb.cpus = "#{NODE_CPU}"
        end

        node.vm.hostname = "#{NODE_NAME}#{i}"
        node.vm.network :private_network, ip: IP_NW + "#{NODE_IP_START + i}"
        node.vm.network "forwarded_port", guest: 22, host: "#{2200 + i}"
    end
  end
end
